version: "3"

services:
  postgres:
    image: fantix/postgres-ssl:13.1
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: Postgres2022!
      POSTGRES_DATABASE: postgres
      PGPASSWORD: Postgres2022@root!
    ports:
      - "15432:5432"
    volumes:
      - 'psql-data:/var/lib/postgresql/data'

    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge

volumes:
  psql-data:
    driver: local
